# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d436e4429b5d1643f3b5e2e21b0025b190aa1cc0e417915b0d4f8ef04b7aa21ddf0665a9ac5862966a7c447b3c83be6b8326f641b040e9ff6268658b20ff55a

test:
  secret_key_base: a2dc0d16c58a07ae7fe53fe418475d8b22315ca88703ba0366658750227adf08710966bde2be0c2e6d3131354fc8d37da0bae3d18fc6e1cdf7a98f08bed8ba37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
